---
- name: Set custom fact based on ansible_system_vendor
  ansible.builtin.set_fact:
    using_gcp: true
  when: ansible_system_vendor == 'Google'

- name: Node dependencies - Set DNF proxy
  ansible.builtin.template:
    src: dnf_proxy.j2
    dest: /etc/dnf/dnf.conf
    mode: '0644'
  become: true
  when:
    - rpm_proxy is defined and rpm_proxy | length > 0
    - (create_pkg_mgr_proxy | default(false)) is true
    - (using_gcp | default(false)) is false

- name: Node dependencies - RPM setup
  tags:
    - node_deps
  become: true
  block:
    - name: Node dependencies - delete unused repos
      ansible.builtin.file:
        name: "{{item}}"
        state: absent
      with_items:
        - /etc/yum.repos.d/fedora-updates-modular.repo
        - /etc/yum.repos.d/fedora-cisco-openh264.repo
    - name: Node dependencies - install base deps
      ansible.builtin.package:
        name:
          - iotop
          - mdadm
          - xfsprogs
        state: present
        use: dnf

- name: Node dependencies - Install RPM packages
  tags:
    - node_deps
  become: true
  ansible.builtin.package:
    name: "{{ rpm_prerequisite_packages }}"
    allowerasing: true
    state: present
    update_cache: true
