---
- name: Node dependencies - Set DNF proxy
  template:
    src: dnf_proxy.j2
    dest: /etc/dnf/dnf.conf
    mode: 0644
  become: true
  when: rpm_proxy is defined and rpm_proxy | length > 0

- name: Node dependencies - RPM setup
  tags:
    - node_deps
  become: true
  block:
    - name: node dependencies - delete unused repos
      ansible.builtin.file:
        name: "{{item}}"
        state: absent
      with_items:
        - /etc/yum.repos.d/fedora-updates-modular.repo
        - /etc/yum.repos.d/fedora-cisco-openh264.repo
    - name: Node dependencies - install base deps
      ansible.builtin.package:
        name:
          - iotop
          - mdadm
          - xfsprogs
        state: present
        use: dnf

- name: Node dependencies - Install RPM packages
  tags:
    - node_deps
  become: true
  package:
    name: "{{ rpm_prerequisite_packages }}"
    state: present
    update_cache: yes
