---
- name: Set fact for package names
  ansible.builtin.set_fact:
    redpanda_version_suffix: "{{ '' if redpanda_version == 'latest' else '-' + redpanda_version }}"
    needs_split_packages: >-
      {{ redpanda_version == 'latest' or 
         (redpanda_version is version('24.2.0', '>=')) or
         development_build | default(false) | bool }}
    allow_lower_version: "{{ development_build | default(false) | bool }}"

- name: Install redpanda (pre 24.2)
  dnf:
    name: "redpanda{{ redpanda_version_suffix }}"
    state: "{{ redpanda_install_status }}"
    update_cache: true
    allow_downgrade: "{{ allow_lower_version }}"
  environment:
    https_proxy: "{{ https_proxy_value | default('') }}"
    http_proxy: "{{ https_proxy_value | default('') }}"
  register: package_result
  when: not needs_split_packages

- name: Install redpanda (post 24.2 or development)
  dnf:
    name:
      - "redpanda-rpk{{ '' if enable_fips == 'disabled' else '-fips'}}{{ redpanda_version_suffix }}"
      - "redpanda{{ redpanda_version_suffix }}"
      {% if enable_fips != 'disabled' %}
      - "redpanda-fips{{ redpanda_version_suffix }}"
      {% endif %}
      - "redpanda-tuner{{ redpanda_version_suffix }}"
    state: "{{ redpanda_install_status }}"
    update_cache: true
    allow_downgrade: "{{ allow_lower_version }}"
  environment:
    https_proxy: "{{ https_proxy_value | default('') }}"
    http_proxy: "{{ https_proxy_value | default('') }}"
  register: package_result
  when: needs_split_packages

- name: Set data dir file perms
  ansible.builtin.file:
    path: "{{ redpanda_data_directory }}"
    owner: redpanda
    group: redpanda
