---
- name: Set fact for package names
  ansible.builtin.set_fact:
    redpanda_version_suffix: "{{ '' if redpanda_version == 'latest' else '-' + redpanda_version }}"
    needs_split_packages: >-
      {{ redpanda_version == 'latest' or 
         (redpanda_version is version('24.2.0', '>=')) or
         development_build | default(false) | bool }}
    allow_lower_version: "{{ development_build | default(false) | bool }}"

- name: check OS FIPS mode state to see if configured and safe for Redpanda to proceed with fips_mode=enabled
  ansible.builtin.include_tasks: fips-assert.yml
  when:
   - enable_fips | default(false) | bool

- name: generate package list to install
  ansible.builtin.set_fact:
    redpanda_package_list: "{{ ['redpanda-rpk-fips', 'redpanda', 'redpanda-fips', 'redpanda-tuner'] if enable_fips | bool else ['redpanda-rpk','redpanda','redpanda-tuner']  }}"

- name: generate versioned package list to install
  ansible.builtin.set_fact:
    redpanda_package_list_versioned: "{{ redpanda_package_list | product([redpanda_version_suffix]) | map('join') | list }}"

- name: Install redpanda (pre 24.2)
  dnf:
    name: "redpanda{{ redpanda_version_suffix }}"
    state: "{{ redpanda_install_status }}"
    update_cache: true
    allow_downgrade: "{{ allow_lower_version }}"
  environment:
    https_proxy: "{{ https_proxy_value | default('') }}"
    http_proxy: "{{ https_proxy_value | default('') }}"
  register: package_result
  when: not needs_split_packages


- name: Install redpanda (post 24.2 or development)
  dnf:
    name: "{{item}}"
    state: "{{ redpanda_install_status }}"
    update_cache: true
    allow_downgrade: "{{ allow_lower_version }}"
  environment:
    https_proxy: "{{ https_proxy_value | default('') }}"
    http_proxy: "{{ https_proxy_value | default('') }}"
  register: package_result
  when: needs_split_packages
  loop: "{{ redpanda_package_list }}"

- name: Set data dir file perms
  ansible.builtin.file:
    path: "{{ redpanda_data_directory }}"
    owner: redpanda
    group: redpanda
