---
- name: Create redpanda group
  ansible.builtin.group:
    name: "{{ redpanda_group }}"
    state: present
    system: true
  become: true
  tags:
    - install_certs


- name: Install certs - create redpanda user if it doesn't exist already
  tags:
    - install_certs
  ansible.builtin.user:
    name: "{{ redpanda_user }}"
    group: "{{ redpanda_group }}"
    system: true
    shell: /usr/sbin/nologin
    create_home: false
    state: present
  become: true

- name: Install certs - ensure /etc/redpanda/certs exists
  tags:
    - install_certs
  ansible.builtin.file:
    path: "{{ redpanda_certs_dir }}"
    state: directory
    owner: redpanda
    group: redpanda
    mode: "0755"

- name: Install_certs - Copy CA Certs
  tags:
    - install_certs
  ansible.builtin.copy:
    src: "{{ ca_cert_file }}"
    dest: "{{ redpanda_truststore_file }}"
    owner: redpanda
    group: redpanda
    force: "{{ overwrite_certs | default('no') | bool }}"
    remote_src: "{{ remote_src_certs | default('no') | bool }}"
    mode: "0644"

- name: Install_certs - Copy Node Certs
  tags:
    - install_certs
  ansible.builtin.copy:
    src: "{{ node_cert_file }}"
    dest: "{{ redpanda_cert_file }}"
    owner: redpanda
    group: redpanda
    force: "{{ overwrite_certs | default('no') | bool }}"
    remote_src: "{{ remote_src_certs | default('no') | bool }}"
    mode: "0644"

- name: Install_certs - Copy Node Keys
  tags:
    - install_certs
  ansible.builtin.copy:
    src: "{{ node_key_file }}"
    dest: "{{ redpanda_key_file }}"
    owner: redpanda
    group: redpanda
    force: "{{ overwrite_certs | default('no') | bool }}"
    remote_src: "{{ remote_src_certs | default('no') | bool }}"
    mode: "0644"
  when:
    - not (node_key_file | default('') == '')
