- name: Create user
  ansible.builtin.include_tasks: create-user.yml

- name: Install JVM
  ansible.builtin.package:
      name: java-17-openjdk
      state: present
  when: not use_existing_jvm | default(false)

- name: Set JAVA_HOME
  ansible.builtin.include_tasks: environment-variables.yml

- name: Copy truststore
  ansible.builtin.include_tasks: copy-truststore.yml
  when: copy_truststore | default(false) | bool

- name: Install Certs
  ansible.builtin.include_tasks: install-certs.yml
  when: copy_keystore | default(false) | bool

- name: Copy keystore
  ansible.builtin.include_tasks: copy-keystore.yml
  when: copy_keystore | default(false) | bool

- name: Install Kafka Connect
  ansible.builtin.include_tasks: install-connect.yml

- name: Configure Kafka Connect
  ansible.builtin.include_tasks: generate-cluster-config.yml

- name: Configure Log4j Config File
  ansible.builtin.include_tasks: generate-log4j-config.yml

- name: Configure Systemd Unit File
  ansible.builtin.include_tasks: generate-unit-file.yml

- name: Restart Redpanda Connect
  ansible.builtin.systemd:
    name: redpanda-connect
    state: restarted
  when: inventory_hostname in groups['connect']
  run_once: true
  delegate_to: "{{ item }}"
  with_items: "{{ groups['connect'] }}"
